### ISSUE TITLE
Updated Data

### ISSUE THREAD

**Issue by matmeylan** [gamba/swiss-geolocation#1]
Hi,

Thanks a lot for this repo, it's been useful.

I was wondering, do you still have the script / commands you used to extract the data ? I would like to update it with the latest data.

Cheers

**Comment by gamba** [comment]
Hey, the service I used to crawl doesn't exists any more because the post publish all the geodeta here: `https://service.post.ch/zopa/dlc/app/#!/main `

You can add coordinates from google with something like 
`http://maps.google.com/maps/api/geocode/json?address=#{zip} #{town}, Switzerland&sensor=false`
